--Q1.What is the total revenue generated by male vs. female customers?
SELECT gender, sum(purchase_amount) as revenue
from customer
group by gender

--Q2.Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied is NOT NULL and purchase_amount>=(select avg(purchase_amount) from customer)

--Q3.Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2)
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4.Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,Round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5.Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select avg(PURCHASE_amount), sum(purchase_amount),subscription_status,count(customer_id)
from customer
group by subscription_status

--A6.Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, Round(100*sum(CASE WHEN (discount_applied ='Yes' THEN 1 ELSE 0 END)/count(*))) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

--Q7.Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases,
CASE
	when previous_purchases=1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)
select customer_segment,count(*) as 'no_of_customers'
from customer_type
group by customer_segment

--Q8.What are the top 3 most purchased products within each category?
with prod_sales as(
SELECT
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rank_num
    FROM customer
    GROUP BY category, item_purchased
)
select category,item_purchased,total_purchases
from prod_sales
WHERE rank_num <= 3
order by category,total_purchases desc

--Q9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeated_buyers
from customer
where previous_purchases>5
groub by subscription_status

--Q10.What is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc